apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: podinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
      nodePort: 30007
